maxLevel: 100
maxExp: "%level% * %level%"
maxChar: 6
skillValue: "%level% * 5"
lossExp: "%level% * 3"
materials:
  head: SKULL_ITEM
  glassPane: STAINED_GLASS_PANE
  leash: LEASH
leaderUpdate: 600

war:
  small: 15
  big: 25
  forcePoints: 500

skills:
  AZURE_DRAGON:
    money: 500.0
    items:
      pistil: 1
  BLACK_TORTOISE:
    money: 500.0
    items:
      pistil: 1
  VERMILION_BIRD:
    money: 500.0
    items:
      pistil: 1
  WHITE_TIGER:
    money: 500.0
    items:
      pistil: 1

dailyContribution:
  money:
    need: 1000.0
    exp: 10.0
    contribute: 100
  points:
    need: 100.0
    exp: 20.0
    contribute: 200

postResources:
  money: 1000.0
  money_contribute: 10
  items:
    pistil: 500

questItems:
  EASY: IRON_INGOT
  NORMAL: GOLD_INGOT
  HARD: DIAMOND
  NIGHTMARE: EMERALD


salaries:
  CO_POPE: 5000
  ELDER: 3000
  CO_ELDER: 2000
  DISCIPLE: 1000
  OUT_DISCIPLE: 500

default_salaries:
  CO_POPE: 5000
  ELDER: 3000
  CO_ELDER: 2000
  DISCIPLE: 1000
  OUT_DISCIPLE: 500
