maxLevel: 100
maxExp: "%level * %level%"
maxChar: 6
skillUpdate: "%level% * 5"
lossExp: "%level% * 3"
materialHead: SKULL
leaderUpdate: 600

dailyContribution:
  money:
    need: 1000.0
    exp: 10.0
    contrubute: 100
  points:
    need: 100.0
    exp: 20.0
    contrubute: 200

postResources:
  money: 1000.0
  money_contribute: 10
  items:
    pistil: 500

questItems:
  EASY: IRON_INGOT
  NORMAL: GOLD_INGOT
  HARD: DIAMOND
  NIGHTMARE: EMERALD


salaries:
  CO_POPE: 5000
  ELDER: 3000
  CO_ELDER: 2000
  DISCIPLE: 1000
  OUT_DISCIPLE: 500

default_salaries:
  CO_POPE: 5000
  ELDER: 3000
  CO_ELDER: 2000
  DISCIPLE: 1000
  OUT_DISCIPLE: 500
