name: LegendGuild
main: com.ericlam.mc.legendguild.LegendGuild
version: ${project.version}
api-version: "1.12"
depend: [KotLib, NBTAPI, PlayerPoints, Vault]
commands:
  guild:
    description: legendguild main command